"""initial schema: users, date_fruit_categories, listings

Revision ID: 579a2b2dee17
Revises:
Create Date: 2026-08-25 03:34:55.433966

This is the only migration the project needs for a fresh install:

    alembic upgrade head

creates the three tables, their indexes and constraints, and then seeds the date
varieties the trained model recognises. Nothing has to be created by hand.
"""
import json
from pathlib import Path
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '579a2b2dee17'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# ---------------------------------------------------------------------------
# HAND-WRITTEN: seeding the model's own categories
#
# Alembic cannot generate this - it only knows about table structure, not about
# rows the application needs in order to work at all.
# ---------------------------------------------------------------------------

# This file lives at <project_root>/backend/alembic/versions/<this>.py, so:
#   parents[0] = versions   parents[1] = alembic
#   parents[2] = backend    parents[3] = <project_root>
# Derived from the file's own location, never hard-coded, so the migration runs
# wherever the project has been cloned.
CLASSES_PATH = Path(__file__).resolve().parents[3] / "model" / "classes.json"


def _canonical(raw: str) -> str:
    """Collapse whitespace and apply Title Case.

    Deliberately duplicated from ``app.models.category.canonical_category_name``
    rather than imported. A migration is a historical record: it must keep doing
    exactly what it did the day it was written, even if the application's own
    helper is changed later. Importing app code into a migration couples the two
    and is a well-known way to make old migrations stop working.
    """
    return " ".join(raw.split()).title()


def _seed_model_categories() -> None:
    """Insert the varieties the Keras model can predict, as source=MODEL.

    Idempotent, by way of ``ON CONFLICT (name) DO NOTHING``: running
    ``alembic upgrade head`` twice, or seeding a database that already holds
    these rows, inserts nothing the second time and raises no error. That is a
    requirement, not a nicety - a migration that fails on a re-run is a
    migration nobody can trust.

    The names come from ``model/classes.json``, which is the single source of
    truth for them. They are NOT typed into this file, because the names, their
    order and their count all belong to the trained model.
    """
    if not CLASSES_PATH.exists():
        raise RuntimeError(
            f"Cannot seed date-fruit categories: {CLASSES_PATH} is missing.\n"
            "model/classes.json must sit next to the model file and contain a "
            'JSON array of the variety names, e.g. ["Ajwa", "Galaxy"].'
        )

    names = json.loads(CLASSES_PATH.read_text(encoding="utf-8"))
    if not isinstance(names, list) or not names:
        raise RuntimeError(
            f"{CLASSES_PATH} must contain a non-empty JSON array of names."
        )

    bind = op.get_bind()
    statement = sa.text(
        """
        INSERT INTO date_fruit_categories (name, source)
        VALUES (:name, 'MODEL')
        ON CONFLICT (name) DO NOTHING
        """
    )
    for raw in names:
        bind.execute(statement, {"name": _canonical(str(raw))})


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('date_fruit_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('source', sa.Enum('MODEL', 'USER', name='category_source'), server_default='USER', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_date_fruit_categories_name'), 'date_fruit_categories', ['name'], unique=True)
    op.create_index(op.f('ix_date_fruit_categories_source'), 'date_fruit_categories', ['source'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('contact_number', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), server_default='1', nullable=False),
    sa.Column('unit', sa.Enum('gram', 'kg', 'piece', name='listing_unit'), nullable=False),
    sa.Column('shop_name', sa.String(length=120), nullable=False),
    sa.Column('contact_number', sa.String(length=30), nullable=False),
    sa.Column('shop_location', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='listing_status'), server_default='ACTIVE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint('price > 0', name='ck_listing_price_positive'),
    sa.CheckConstraint('quantity > 0', name='ck_listing_quantity_positive'),
    sa.ForeignKeyConstraint(['category_id'], ['date_fruit_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listings_category_id'), 'listings', ['category_id'], unique=False)
    op.create_index('ix_listings_category_status_price', 'listings', ['category_id', 'status', 'price'], unique=False)
    op.create_index(op.f('ix_listings_status'), 'listings', ['status'], unique=False)
    op.create_index(op.f('ix_listings_user_id'), 'listings', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # --- HAND-WRITTEN ADDITION (do not delete) -----------------------------
    # The tables are empty at this point. The application is unusable without
    # the model's own categories, so they are inserted as part of the same
    # migration: `alembic upgrade head` leaves a database ready to use.
    _seed_model_categories()


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listings_user_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_status'), table_name='listings')
    op.drop_index('ix_listings_category_status_price', table_name='listings')
    op.drop_index(op.f('ix_listings_category_id'), table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_date_fruit_categories_source'), table_name='date_fruit_categories')
    op.drop_index(op.f('ix_date_fruit_categories_name'), table_name='date_fruit_categories')
    op.drop_table('date_fruit_categories')
    # ### end Alembic commands ###

    # --- HAND-WRITTEN ADDITION (do not delete) -----------------------------
    # `upgrade()` creates three PostgreSQL ENUM types as a side effect of
    # create_table: category_source, listing_unit and listing_status. Alembic's
    # autogenerate does NOT write the matching DROP TYPE statements, so without
    # these lines the types survive a downgrade as orphans and the next
    # `alembic upgrade head` fails with:
    #     psycopg.errors.DuplicateObject: type "listing_status" already exists
    # `checkfirst=True` keeps the drop safe even if the type is already gone.
    bind = op.get_bind()
    sa.Enum(name='listing_status').drop(bind, checkfirst=True)
    sa.Enum(name='listing_unit').drop(bind, checkfirst=True)
    sa.Enum(name='category_source').drop(bind, checkfirst=True)
